### ISSUE TITLE
fontdiff doesn't consider font-weights

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/fontdiff#12] opened 2016-12-05 20:28 UTC
I used fontdiff to compare Phase 3 normal TTF with a Phase 3 GX font and found that fontdiff doesn't consider "font-weight:400" in the specimen HTML and render Black weight of GX font.

~/fontdiff/build/out/Default/fontdiff --before P3TTF/NotoSansKhmer-Regular.ttf --after GX/NotoSansKhmer-GX.ttf --specimen sample_html_pages/km-Khmr_udhr.html --out out/kmGXP3TTF.PDF

<html lang="km">
  <p><span style="font-weight:400">មនុស្សទាំងអស់ កើតមកមានសេរីភាព និងសមភាព ក្នុងផ្នែកសេចក្ដីថ្លៃថ្នូរនិងសិទ្ធិ។ មនុស្ស មានវិចារណញ្ញាណនិងសតិសម្បជញ្ញៈជាប់ពីកំណើត ហើយគប្បីប្រព្រឹត្ដចំពោះគ្នាទៅវិញទៅមក ក្នុង ស្មារតីភាតរភាពជាបងប្អូន។</span></p>
</html>

@jamesgk

**Comment by jamesgk** [comment] 2016-12-05 20:38
Attaching HTML, PDF and fonts for reference.

[km-Khmr_udhr.html.zip](https://github.com/googlei18n/fontdiff/files/632215/km-Khmr_udhr.html.zip)
[km.pdf](https://github.com/googlei18n/fontdiff/files/632216/km.pdf)
[NotoSansKhmer-Regular.ttf.zip](https://github.com/googlei18n/fontdiff/files/632217/NotoSansKhmer-Regular.ttf.zip)
[NotoSansKhmer-GX.ttf.zip](https://github.com/googlei18n/fontdiff/files/632218/NotoSansKhmer-GX.ttf.zip)

**Comment by brawer** [comment] 2016-12-06 07:59
The input font is broken because [fontmake produces invalid fonts](https://github.com/googlei18n/fontmake/issues/167). Specifically, the `wght` axis of the input font “NotoSamsKhmer-GX.ttf” is invalid: according to the [OpenType specification](https://www.microsoft.com/typography/otspec/fvar.htm#VAT), weight values must be such they can “interpreted in direct comparison to the CSS font-weight property”. Currently, this is not the case:

```xml
    <!-- Weight -->
    <Axis>
      <AxisTag>wght</AxisTag>
      <MinValue>26.0</MinValue>
      <DefaultValue>90.0</DefaultValue>
      <MaxValue>190.0</MaxValue>
      <AxisNameID>257</AxisNameID>
    </Axis>
```

**Comment by brawer** [comment] 2016-12-06 08:57
Closing this bug here because the problem is in fontmake, not in fontdiff. But of course https://github.com/googlei18n/fontmake/issues/167 needs to be fixed.

**Closed by brawer** 2016-12-06 08:57 UTC
